export const environment = {
  production: true,
  // Domain:'https://invui.azurewebsites.net/',
  // Group: 'https://invui.azurewebsites.net/api/Groups/',
  // SubGroup: 'https://invui.azurewebsites.net/api/SubGroups/',
  // Items: 'https://invui.azurewebsites.net/api/Items/',
  // GetGroupBySubGroupId:'https://invui.azurewebsites.net/api/SubGroups/GetGroupBySubGroupId/',
  // uploadFile:'https://invui.azurewebsites.net/api/Items/api/dashboard/UploadDocuments',
  // ItemDocuments:'https://invui.azurewebsites.net/api/ItemDocuments/',
  // employees: 'https://invui.azurewebsites.net/api/Employees/',
  // ItemStatusEmps: 'https://invui.azurewebsites.net/api/ItemStatusEmps/',
  // GetAllStatusesByItemId:'https://invui.azurewebsites.net/api/ItemStatusEmps/GetAllStatusesByItemId/',
  // GetItemDocumentsItemId:'https://invui.azurewebsites.net/api/ItemDocuments/GetItemDocumentsItemId/',
  // GetImage:'https://invui.azurewebsites.net/Items/getImage/',
  // User: 'https://invui.azurewebsites.net/api',
  // GetSubGroupsByGroupId:"https://invui.azurewebsites.net/api/SubGroups/GetSubGroupsByGroupId/",
  // Active:'https://invui.azurewebsites.net/api/SubGroups/Active/',
  Domain:'http://10.10.0.129/InventoryApiPublish/',
  Group: 'http://10.10.0.129/InventoryApiPublish/api/Groups/',
  SubGroup: 'http://10.10.0.129/InventoryApiPublish/api/SubGroups/',
  Items: 'http://10.10.0.129/InventoryApiPublish/api/Items/',
  GetGroupBySubGroupId:'http://10.10.0.129/InventoryApiPublish/api/SubGroups/GetGroupBySubGroupId/',
  uploadFile:'http://10.10.0.129/InventoryApiPublish/api/Items/api/dashboard/UploadDocuments',
  ItemDocuments:'http://10.10.0.129/InventoryApiPublish/api/ItemDocuments/',
  employees: 'http://10.10.0.129/InventoryApiPublish/api/Employees/',
  ItemStatusEmps: 'http://10.10.0.129/InventoryApiPublish/api/ItemStatusEmps/',
  GetAllStatusesByItemId:'http://10.10.0.129/InventoryApiPublish/api/ItemStatusEmps/GetAllStatusesByItemId/',
  GetItemDocumentsItemId:'http://10.10.0.129/InventoryApiPublish/api/ItemDocuments/GetItemDocumentsItemId/',
  GetImage:'http://10.10.0.129/InventoryApiPublish/Items/getImage/',
  User: 'http://10.10.0.129/InventoryApiPublish/api',
  GetSubGroupsByGroupId:"http://10.10.0.129/InventoryApiPublish/api/SubGroups/GetSubGroupsByGroupId/",
  Active:'http://10.10.0.129/InventoryApiPublish/api/SubGroups/Active/',
};
